version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.13.3-management   
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "desafiopb"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
    networks:
      - ntw-default-zone
  
  cadastro-cliente-zone-01:
    build: 
      context: .
      dockerfile: ./src/DesafioPB.CadastroCliente/Dockerfile
    restart: always
    healthcheck:
      test: curl --fail http://localhost || exit -1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    depends_on:
      - rabbitmq
    ports:
      - 7001:80
    networks:
      - ntw-default-zone
 
  cartao-de-credito-zone-01:
    build:  
      context: .
      dockerfile: ./src/DesafioPB.CartaoDeCredito/Dockerfile
    restart: always
    healthcheck:
      test: curl --fail http://localhost || exit -1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    depends_on:
      - rabbitmq
    ports:
      - 7002:80
    networks:
      - ntw-default-zone

  proposta-credito-zone-01:
    build:  
      context: .
      dockerfile: ./src/DesafioPB.PropostaCredito/Dockerfile
    restart: always
    healthcheck:
      test: curl --fail http://localhost || exit -1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    depends_on:
      - rabbitmq
    ports:
      - 7003:80
    networks:
      - ntw-default-zone

networks:
  ntw-default-zone:
    driver: bridge